const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const CORS={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"content-type,x-admin-password"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...CORS}})}
function authed(r,e){return !!e.ADMIN_PASSWORD&&(r.headers.get('x-admin-password')||'')===e.ADMIN_PASSWORD}
async function parsePost(r){const b=await r.json();if(!b.title||!b.category||!b.section)throw Error('Не заполнены обязательные поля.');return {title:String(b.title).trim().slice(0,200),category:String(b.category).slice(0,100),section:String(b.section).slice(0,30),excerpt:String(b.excerpt||'').slice(0,2000),image:String(b.image||'').slice(0,3000),blocks:Array.isArray(b.blocks)?b.blocks.map(x=>({type:String(x.type||'text'),heading:String(x.heading||'').slice(0,200),text:String(x.text||'').slice(0,20000),image:String(x.image||'').slice(0,3000),caption:String(x.caption||'').slice(0,500)})).slice(0,30):[]}}
export default{async fetch(r,e){const u=new URL(r.url);if(r.method==='OPTIONS')return new Response(null,{headers:CORS});
if(u.pathname==='/api/posts'&&r.method==='GET'){const {results}=await e.DB.prepare('SELECT id,title,category,section,excerpt,image,blocks,created_at FROM posts ORDER BY created_at DESC').all();return json((results||[]).map(p=>({...p,blocks:JSON.parse(p.blocks||'[]')})))}
if(u.pathname==='/api/admin/check'&&r.method==='POST')return json({ok:authed(r,e)},authed(r,e)?200:401);
if(u.pathname==='/api/posts'&&r.method==='POST'){if(!authed(r,e))return json({error:'Unauthorized'},401);try{const b=await parsePost(r),id=crypto.randomUUID();await e.DB.prepare('INSERT INTO posts(id,title,category,section,excerpt,image,blocks,created_at) VALUES(?,?,?,?,?,?,?,datetime(\'now\'))').bind(id,b.title,b.category,b.section,b.excerpt,b.image,JSON.stringify(b.blocks)).run();return json({ok:true,id})}catch(x){return json({error:x.message},400)}}
if(u.pathname.startsWith('/api/posts/')&&(r.method==='PUT'||r.method==='DELETE')){if(!authed(r,e))return json({error:'Unauthorized'},401);const id=decodeURIComponent(u.pathname.slice(11));if(r.method==='DELETE'){await e.DB.prepare('DELETE FROM posts WHERE id=?').bind(id).run();return json({ok:true})}try{const b=await parsePost(r);await e.DB.prepare('UPDATE posts SET title=?,category=?,section=?,excerpt=?,image=?,blocks=? WHERE id=?').bind(b.title,b.category,b.section,b.excerpt,b.image,JSON.stringify(b.blocks),id).run();return json({ok:true})}catch(x){return json({error:x.message},400)}}
return e.ASSETS.fetch(r)}};
